### ISSUE TITLE
Title?

### ISSUE THREAD

**Issue by mirek** [paul/progress_bar#28]
Great progress, what about squeezing optional title on the left? Ideally ellipsized if there's no room?

**Comment by paul** [comment]
Not a bad idea, I'd be happy to accept a pull request with an implementation. However, why not just simply `puts` the title you want before calling `bar.increment!` the first time? That's how I commonly do it:

```
==> Loading stuff...
[##############][3/s][etc]

==> Reticulating Splines
[###           ][17/s][etc]
```

**Comment by mirek** [comment]
Yes, printing line above works ok'ish and that's what I've been doing but I've got quite a lot of tasks to process, some of them take longer, some are very fast, instead of cluttered output i prefer to have single line with changing title. I've put PR for title with `examples/step.rb`. It makes title optional and compatible with current public API.
