### ISSUE TITLE
Remove protected for ProgressBar methods.

### ISSUE THREAD

**Issue by jasonm23** [paul/progress_bar#59]
To help people customize/extend `ProgressBar` for their specific use cases, it'd be great if there was no `protected` method access.

I'm wondering why those methods were protected in the first place?

More than happy to submit the 1 line PR if needed. 👍🏻

**Comment by jasonm23** [comment]
Ok, I'll admit it, I forgot that protected doesn't stop monkey patching... so closing.

**Comment by paul** [comment]
@jasonm23 What sort of customizations were you looking to do? Awhile back I hacked together a way to "theme" the bar, but never finished because it wasn't something I needed personally. https://github.com/paul/progress_bar/pull/45#issuecomment-532882023

**Comment by jasonm23** [comment]
I just override render_bar and change the `#` to a `░` 

It'd be pretty easy to allow this as a user option on the script using `progress_bar`.
